"""empty message

Revision ID: 2bfdce8a5fcb
Revises: d337d26e82f6
Create Date: 2025-12-21 18:47:35.142695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfdce8a5fcb'
down_revision: Union[str, Sequence[str], None] = 'd337d26e82f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mission_content', sa.String(), nullable=False))
        batch_op.alter_column('mission_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.alter_column('mission_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('mission_content')

    # ### end Alembic commands ###
